config/routes.rb
AddressBook::Application.routes.draw do
  resources :entries
  root :to => "entries#index"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :address, :email, :name, :phone
  validates_presence_of :name, :phone, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entry = Entry.new
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.js
      
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
    respond_to do |format|
      format.html 
      format.js
    end
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html 
        format.js
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.js
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.js
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<tr id="<%= dom_id entry %>">
  <td><%= entry.name %></td>
  <td><%= entry.address %></td>
  <td><%= entry.phone %></td>
  <td><%= entry.email %></td>
  <td><%= link_to 'Show', entry %></td>
  <td><%= link_to 'Edit', edit_entry_path(entry), :remote => true %></td>
  <td><%= link_to 'Destroy', entry, :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
</tr>

app/views/entries/_form.html.erb
<%= form_for(@entry, :remote => true) do |f| %>
      
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/create.html.erb
<h1>Creating entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/create.js.erb
//$('#entries').append('<%= j render(:partial => "form")%>');
//$("#new_entry")[0].reset();


 /*Update the html of the div flash_notice with the new one*/
//  $("#new_entry").html("<%= escape_javascript(flash[:notice])%>");

  /*Show the flash_notice div*/
  //$("#new_entry").show(300);

  /*Clear the entire form*/
  //$(":input:not(input[type=submit])").val("");

  /*Replace the html of the div post_lists with the updated new one*/
  //$("#entries").html("<%= escape_javascript( render(:partial => "form") ) %>");
//<% end -%>
//$('#new_entry').remove();
//$('#new_entry_link').show();
//$('#entries').append(' @entry)%>');

<% if @entry.errors.count == 0 %>

	$('#new_entry').remove();
	$('#new_entry_link').show();
	$('#entries').append('<%= j render("entry", :entry => @entry) %>');

<% else %>

	$('.new_entry').remove();
	$('#new_entry_link').after('<%= j render("form") %>');

<% end %>

app/views/entries/destroy.js.erb
$('#<%= dom_id @entry %>').remove();

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/edit.js.erb
$("#form > form").replaceWith("<%= escape_javascript(render(:partial => "form"))%>")

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tbody id="entries">

<% @entries.each do |entry| %>
  <%= render "entry", :entry => entry%> 
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Entry', new_entry_path, remote: true, :id => "new_entry_link" %>


<h2>Entry form</h2>
<div id="form">
  <%= render :partial => "form" %>
</div> 

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @entry.name %>
</p>

<p>
  <b>Address:</b>
  <%= @entry.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @entry.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @entry.email %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/entries/update.js.erb
$("#<%= dom_id(@entry) %>").replaceWith("<%= escape_javascript(render(:partial => @entry)) %>");
<% @entry = Entry.new # reset for new form %>
$(".edit_entry").replaceWith("<%= escape_javascript(render(:partial => "form"))%>")
$(".new_entry")[0].reset();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>